openapi: 3.0.3
info:
  title: Elice SW Track 7th Web Project Team 5 - 온앤오프
  description: API 문서
  version: 1.0.0
servers:
  - url: http://localhost:4000/api
tags:
  - name: careerCategories
    description: 직업 카테고리 API
  - name: categories
    description: 카테고리 API

paths:
  /careerCategories:
    get:
      tags:
        - careerCategories
      summary: 직업 카테고리 목록
      description: 직업 카테고리 목록을 가져오는 API
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CareerCategory'
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

    post:
      tags:
        - careerCategories
      summary: 직업 카테고리 등록
      description: 직업 카테고리를 등록하는 API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 학생
        required: true
      responses:
        '201':
          description: 성공
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

  /careerCategories/{id}:
    get:
      tags:
        - careerCategories
      summary: 직업 카테고리 상세
      description: 직업 카테고리 상세정보을 가져오는 API
      parameters:
        - name: id
          in: path
          description: 직업 카테고리 ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CareerCategory'
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

    put:
      tags:
        - careerCategories
      summary: 직업 카테고리 수정
      description: 직업 카테고리 정보를 수정하는 API
      parameters:
        - name: id
          in: path
          description: 직업 카테고리 ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 학생
        required: true
      responses:
        '200':
          description: 성공
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

    delete:
      tags:
        - careerCategories
      summary: 직업 카테고리 삭제
      description: 직업 카테고리 정보를 삭제하는 API
      parameters:
        - name: id
          in: path
          description: 직업 카테고리 ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 성공
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

  /categories:
    get:
      tags:
        - categories
      summary: 카테고리 목록
      description: 카테고리 목록을 가져오는 API
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

    post:
      tags:
        - categories
      summary: 카테고리 등록
      description: 카테고리를 등록하는 API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 크루
                flag:
                  type: number
                  example: 0
      responses:
        '201':
          description: 성공
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

  /categories/{categoryId}:
    get:
      tags:
        - categories
      summary: 카테고리 상세
      description: 카테고리 상세정보을 가져오는 API
      parameters:
        - name: categoryId
          in: path
          description: 카테고리 ID
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

    put:
      tags:
        - categories
      summary: 카테고리 수정
      description: 카테고리 정보를 수정하는 API
      parameters:
        - name: categoryId
          in: path
          description: 카테고리 ID
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 크루
                flag:
                  type: number
                  example: 0
        required: true
      responses:
        '200':
          description: 성공
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

    delete:
      tags:
        - categories
      summary: 카테고리 삭제
      description: 카테고리 정보를 삭제하는 API
      parameters:
        - name: categoryId
          in: path
          description: 카테고리 ID
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 성공
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

  /categories/{categoryId}/subCategories:
    get:
      tags:
        - categories
      summary: 서브 카테고리 상세
      description: 서브 카테고리 상세정보을 가져오는 API
      parameters:
        - name: categoryId
          in: path
          description: 부모 카테고리 ID
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubCategory'
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

    post:
      tags:
        - categories
      summary: 서브 카테고리 등록
      description: 서브 카테고리를 등록하는 API
      parameters:
        - name: categoryId
          in: path
          description: 부모 카테고리 ID
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 외국어
      responses:
        '201':
          description: 성공
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러
  
  /categories/{categoryId}/subCategories/{subCategoryId}:
    get:
      tags:
        - categories
      summary: 서브 카테고리 상세
      description: 서브 카테고리 상세정보을 가져오는 API
      parameters:
        - name: categoryId
          in: path
          description: 카테고리 ID
          required: true
          schema:
            type: number
        - name: subCategoryId
          in: path
          description: 서브 카테고리 ID
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubCategory'
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

    put:
      tags:
        - categories
      summary: 서브 카테고리 수정
      description: 서브 카테고리 정보를 수정하는 API
      parameters:
        - name: categoryId
          in: path
          description: 카테고리 ID
          required: true
          schema:
            type: number
        - name: subCategoryId
          in: path
          description: 서브 카테고리 ID
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 크루
        required: true
      responses:
        '200':
          description: 성공
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러

    delete:
      tags:
        - categories
      summary: 서브 카테고리 삭제
      description: 서브 카테고리 정보를 삭제하는 API
      parameters:
        - name: categoryId
          in: path
          description: 카테고리 ID
          required: true
          schema:
            type: number
        - name: subCategoryId
          in: path
          description: 서브 카테고리 ID
          required: true
          schema:
            type: number
      responses:
        '200':
          description: 성공
        '4xx':
          description: 잘못된 요청
        '5xx':
          description: 서버 에러


















components:
  schemas:
    CareerCategory:
      required:
        - _id
        - name
        - createdAt
        - updatedAt
      type: object
      properties:
        _id:
          type: number
          example: 1
          description: Primary Key
        name:
          type: string
          example: 학생
          description: 직업 카테고리 이름
        createdAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 등록날짜
        updatedAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 수정날짜
        deletedAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 삭제날짜


    CareerCategory:
      required:
        - _id
        - name
        - createdAt
        - updatedAt
      type: object
      properties:
        _id:
          type: number
          example: 1
          description: Primary Key
        name:
          type: string
          example: 학생
          description: 직업 카테고리 이름
        createdAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 등록날짜
        updatedAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 수정날짜
        deletedAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 삭제날짜


    Category:
      required:
        - _id
        - name
        - createdAt
        - updatedAt
      type: object
      properties:
        _id:
          type: number
          example: 1
          description: Primary Key
        name:
          type: string
          example: 크루
          description: 카테고리 이름
        flag:
          type: number
          example: 0
          default: 0
          description: 0 기간설정 불가능, 1 기간설정가능 (default 0)
        createdAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 등록날짜
        updatedAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 수정날짜
        deletedAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 삭제날짜
        categories:
          type: array
          items:
            $ref: '#/components/schemas/SubCategory'

    SubCategory:
      required:
        - _id
        - name
        - createdAt
        - updatedAt
      type: object
      properties:
        _id:
          type: number
          example: 1
          description: Primary Key
        name:
          type: string
          example: 크루
          description: 카테고리 이름
        createdAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 등록날짜
        updatedAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 수정날짜
        deletedAt:
          type: string
          example: 2023-12-01T17:32:28Z
          description: 삭제날짜

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
